name: Deployment

on:
  push:
    branches:
      - master
    paths:
      - .firebase/database-rules.json
      - .firebase/firestore.rules
      - .firebase/storage.rules
      - .github/workflows/deployment.yml
      - '*/src/**'
      - '**/package.json'

env:
  BASE_URL: https://admin.feryardiant.id/
  PROJECT_ID: fery-wardiyanto

jobs:
  deploy:
    runs-on: ubuntu-20.04

    environment:
      name: production
      url: ${{ env.BASE_URL }}

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Cache
      uses: actions/cache@v2
      env:
        cache-name: pnpm-cache
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-

    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.10
        run_install: true

    - name: Build
      run: pnpm build

    - name: Deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        SENDGRID_KEY: ${{ secrets.SENDGRID_KEY }}
        VITE_FIREBASE_APPID: ${{ secrets.FIREBASE_APPID }}
        VITE_FIREBASE_APIKEY: ${{ secrets.FIREBASE_APIKEY }}
        VITE_FIREBASE_MEASUREMENTID: ${{ secrets.FIREBASE_MEASUREMENTID }}
        VITE_FIREBASE_MESSAGINGSENDERID: ${{ secrets.FIREBASE_MESSAGINGSENDERID }}
        VITE_FIREBASE_PROJECTID: ${{ env.PROJECT_ID }}
        VITE_RECAPTCHA_SITEKEY: ${{ secrets.RECAPTCHA_SITEKEY }}
        VITE_RECAPTCHA_SECRETKEY: ${{ secrets.RECAPTCHA_SECRETKEY }}
      run: pnpm deploy -- --token "$FIREBASE_TOKEN"
